project_id = "hmqlxknwiszxqvzlisum"

[functions.create-checkout-session]
verify_jwt = true

[functions.create-customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-smart-alerts]
verify_jwt = true
